# To run the server (from the directory containing the app.py file): 
#   poetry run uvicorn app:app --reload

# uvicorn - ASGI web server (https://www.uvicorn.org/).
# --reload - automatically reload app after each change.
import time
from fastapi import FastAPI, Request
from fastapi.responses import StreamingResponse
from starlette.datastructures import URL

app = FastAPI()

# Returns a "JSONResponse" object.
@app.get("/info")
async def info(timestamp: float = None):
    return { "msg": "My first FastAPI application" }

@app.get("/v2/info")
async def info_v2():
    return { "msg": "Version 2 of my first application" }

def add_timestamp_param_to_request_url(request: Request, timestamp: int):
    parsed_url = URL(request.url)
    query_paramas = parsed_url.query_params
    query_paramas
    
    request.url = parsed_url

# Function-based middleware definition.
# `request` = all information associated with the incoming request.
# `call_next` = function that returns a response generated by the endpoint.
# It has an access to the incoming request (by the `request` param) and to
# the outgoing response (returned by the `call_next` function).
@app.middleware("http")
async def set_timestamp_on_request_and_response(request: Request, call_next):
    given_timestamp = request.query_params.get("timestamp")

    # Add timestamp to the request.
    if not given_timestamp:
        given_timestamp = int(time.time())
        add_timestamp_param_to_request_url(request, given_timestamp)

    # Process the modified request and intercept the response
    response = await call_next(request)

    # Add custom header to the response
    if isinstance(response, StreamingResponse):
        response.headers["X-Timestamp"] = str(given_timestamp)

    return response